//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gta2dll.rc
//
#define IDD_DIALOG1                     3000
#define IDC_PEDX                        3001
#define IDC_PEDHEALTH                   3002
#define IDC_PEDY                        3003
#define IDC_PEDZ                        3004
#define IDC_PEDARMOR                    3005
#define IDC_PEDROT                      3006
#define IDC_PEDSAMMO                    3007
#define IDC_PEDSTYPE                    3008
#define IDC_PEDSTIME                    3009
#define IDC_UNLMAMMO                    3010
#define IDC_STAR0                       3011
#define IDC_STAR1                       3012
#define IDC_STAR2                       3013
#define IDC_STAR3                       3014
#define IDC_STAR4                       3015
#define IDC_STAR5                       3016
#define IDC_STAR6                       3017
#define IDC_STARCOUNTER                 3018
#define IDC_LOCKCOPLEVEL                3019
#define IDC_CARENGINEOFF                3020
#define IDC_CARFIX                      3021
#define IDC_CARVISFIX                   3022
#define IDC_CARDAMAGE                   3023
#define IDC_PREMAP_S                    3024
#define IDC_CARID                       3025
#define IDC_CARLASTTP                   3027
#define IDC_CARVIS                      3028
#define IDC_PEDMONEY                    3029
#define IDC_PEDS0TIME                   3031
#define IDC_PEDIMMORT                   3032
#define IDC_PEDHAMSET                   3033
#define IDC_BEAHUMAN                    3034
#define IDC_GANG1V                      3035
#define IDC_GANG2V                      3036
#define IDC_GANG3V                      3037
#define IDC_CARVEL                      3038
#define IDC_FREESHOP                    3039
#define IDC_GANG1M                      3040
#define IDC_GANG1Z                      3041
#define IDC_GANG1P                      3042
#define IDC_GANG2M                      3043
#define IDC_GANG2Z                      3044
#define IDC_GANG2P                      3045
#define IDC_GANG3M                      3046
#define IDC_GANG3Z                      3047
#define IDC_GANG3P                      3048
#define IDC_CARVISBRK                   3049
#define IDC_MOUSECTRL                   3050
#define IDC_PASSENGER                   3051
#define IDC_CARCOLM                     3052
#define IDC_CARCOLP                     3053
#define IDC_CARCOLV                     3054
#define IDC_CARCOLR                     3055
#define IDC_GOSLOW                      3056
#define IDC_PREMAP_R                    3057
#define IDC_CARDUMMY                    3058
#define IDC_BIGTEXTTEXT                 3063
#define IDC_BIGTEXTSHOW                 3064
#define IDC_CARTRCOLR                   3065
#define IDC_PEDSHAPECLOTHR              3066
#define IDC_CARINVALL                   3067
#define IDC_CARINVBUL                   3068
#define IDC_CARINVFLM                   3069
#define IDC_CARINVRKT                   3070
#define IDC_CARINVCOL                   3071
#define IDC_CARNOCOL                    3072
#define IDC_PREMAP_DEF                  3073
#define IDC_CARINFO                     3074
#define IDC_DOOR1                       3075
#define IDC_DOOR2                       3076
#define IDC_DOOR3                       3077
#define IDC_DOOR4                       3078
#define IDC_EMBCUR                      3079
#define IDC_EMBP                        3080
#define IDC_EMBM                        3081
#define IDC_EMBPOS                      3082
#define IDC_CAREXPLODE                  3083
#define IDC_BANNER                      3084
#define IDB_BANNER                      3085
#define IDC_EDIT1                       3086
#define IDD_ACS                         4000
#define IDC_ACS_SPAWN                   4001
#define IDC_ACS_X                       4002
#define IDC_ACS_Y                       4003
#define IDC_ACS_Z                       4004
#define IDC_ACS_ROT                     4005
#define IDC_ACS_GETPPOS                 4006
#define IDC_ACS_XSIZE                   4007
#define IDC_ACS_YSIZE                   4008
#define IDC_ACS_XOFF                    4009
#define IDC_ACS_YOFF                    4010
#define IDC_ACS_VCOLORS                 4011
#define IDC_ACS_MODEL                   4012
#define IDC_ACS_MINICAR                 4013
#define IDD_LT                          4500
#define IDC_LT_LIST                     4501
#define IDC_LT_MODE                     4502
#define IDC_LT_UPDATE                   4503
#define IDC_LT_EDIT                     4504
#define IDC_LT_SORT                     4505
#define IDD_LTE                         4600
#define IDC_LTE_LIST_SEL                4601
#define IDC_LTE_LIST_AVA                4602
#define IDC_LTE_DEFAULTS                4603
#define IDC_LTE_UP                      4604
#define IDC_LTE_ADD                     4605
#define IDC_LTE_DOWN                    4606
#define IDC_LTE_REMOVE                  4607
#define IDD_PS                          5000
#define IDC_PS_SPAWN                    5001
#define IDC_PS_X                        5002
#define IDC_PS_Y                        5003
#define IDC_PS_Z                        5004
#define IDC_PS_ROT                      5005
#define IDC_PS_GETPPOS                  5006
#define IDC_PS_PRESET                   5007
#define IDC_PS_SHAPE                    5008
#define IDC_PS_REMAP                    5009
#define IDC_PS_WEAP                     5010
#define IDC_PS_HEALTH                   5011
#define IDC_PS_OCCUP                    5012
#define IDC_PS_THR_S                    5013
#define IDC_PS_THR_R                    5014
#define IDC_PS_AI0                      5015
#define IDC_PS_AI1                      5016
#define IDC_PS_AI2                      5017
#define IDC_PS_AI3                      5018
#define IDC_PS_AI4                      5019
#define IDC_PS_AI5                      5020
#define IDC_PS_AI6                      5021
#define IDC_PS_AI7                      5022
#define IDC_PS_AI8                      5023
#define IDC_PS_AI9                      5024
#define IDC_PS_AI10                     5025
#define IDC_PS_AI11                     5026
#define IDC_PS_AI12                     5027
#define IDC_PS_AI13                     5028
#define IDC_PS_AI14                     5029
#define IDC_PS_LEADER                   5030
#define IDC_PS_INCAR                    5031
#define IDC_PS_OBJ                      5032
#define IDC_PS_OBJTIMER                 5033
#define IDC_PS_OBJT_X                   5034
#define IDC_PS_OBJT_Y                   5035
#define IDC_PS_OBJT_Z                   5036
#define IDC_PS_OBJT_XL                  5037
#define IDC_PS_OBJT_YL                  5038
#define IDC_PS_OBJT_ZL                  5039
#define IDD_CAM                         6000
#define IDC_CAM_X                       6001
#define IDC_CAM_Y                       6002
#define IDC_CAM_Z                       6003
#define IDC_CAM_ZOOM                    6004
#define IDC_CAM_SYNC                    6005
#define IDC_CAM_TP                      6006
#define IDC_CAM_FPED                    6007
#define IDC_CAM_FPL                     6008
#define IDC_CAM_ZL                      6009
#define IDC_CAM_ZOOML                   6010
#define IDC_CAM_TARL                    6011
#define IDC_CAM_UP                      6012
#define IDC_CAM_DOWN                    6013
#define IDC_CAM_LEFT                    6014
#define IDC_CAM_RIGHT                   6015
#define IDC_CAM_ZUP                     6016
#define IDC_CAM_ZDOWN                   6017
#define IDC_CAM_SEN                     6018
#define IDC_CAM_AA                      6019
#define IDC_CAM_SHADOWS                 6020
#define ID_COMMANDS_HELLO               32000
#define ID_COMMANDS_TANK                32001
#define ID_COMMANDS_GUNJEEP             32002
#define ID_COMMANDS_HIJACKATRAIN        32003
#define ID_COMMANDS_EXPLODECARS         32004
#define ID_COMMANDS_TPALLPEDS           32005
#define ID_COMMANDS_LIVETABLE           32006
#define ID_COMMANDS_GT24640             32007
#define ID_COMMANDS_CAMERA              32008
#define ID_SPAWNCAR                     35000
#define ID_SPAWNCAR_LAST                35001
#define ID_SPAWNCAR_ARRAY               35002
#define ID_SPAWNCAR_START               35003
#define ID_SPAWNOBJ                     36000
#define ID_SPAWNOBJ_LAST                36001
#define ID_SPAWNOBJ_START               36002
#define ID_SPAWNPED                     36500
#define ID_SPAWNPED_TOOL                36501
#define ID_GETWEAP                      37000
#define ID_GETWEAP_ALL                  37001
#define ID_GETWEAP_START                37002
#define ID_GETCARWEAP                   37100
#define ID_GETCARWEAP_START             37101
#define ID_VOCALS                       37200
#define ID_VOCALS_START                 37201
#define ID_NATIVE                       38000
#define ID_NATIVE_START                 38001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3019
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         3136
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
